//! Built-in knowledge of what commonly eats a Mac's disk and is safe to lose.
//!
//! Matching is done on a directory's *siblings*, not on its name alone. A
//! folder called `target` is only a Rust build directory when there is a
//! `Cargo.toml` next to it; `node_modules` only means what you think next to a
//! `package.json`. Name-only matching would eventually stage someone's photos.

use std::collections::HashSet;

#[derive(
    Clone, Copy, Debug, Hash, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
pub enum Category {
    /// Virtual machine and container disk images. Usually the single biggest
    /// thing on a developer's Mac.
    VmImage,
    /// Rebuilt by running the build again.
    BuildArtifact,
    /// Re-downloaded on demand.
    PackageCache,
    /// Regenerated by the app that owns them.
    AppCache,
}

impl Category {
    pub fn label(self) -> &'static str {
        match self {
            Category::VmImage => "VM images",
            Category::BuildArtifact => "build artifacts",
            Category::PackageCache => "package caches",
            Category::AppCache => "app caches",
        }
    }

    /// What the user needs to know before staging the whole category.
    pub fn note(self) -> &'static str {
        match self {
            Category::VmImage => "the VM or container must be stopped first",
            Category::BuildArtifact => "rebuilt by your next build",
            Category::PackageCache => "re-downloaded on demand",
            Category::AppCache => "regenerated by the app that owns them",
        }
    }

    pub fn all() -> [Category; 4] {
        [Category::VmImage, Category::BuildArtifact, Category::PackageCache, Category::AppCache]
    }
}

/// A build directory, the marker file that proves what it is, and the command
/// that puts it back.
///
/// The third column is the whole reason the marker is checked by name rather
/// than by "does a build system live here": having proved which tool made this
/// directory, we can tell the user exactly what to run to get it back. "Rebuilt
/// by your next build" is reassurance; `cargo build` is an answer.
const BUILD_DIRS: &[(&str, &[&str], &str)] = &[
    ("node_modules", &["package.json"], "npm install"),
    ("target", &["Cargo.toml"], "cargo build"),
    ("build", &["CMakeLists.txt"], "cmake --build build"),
    ("build", &["build.gradle", "build.gradle.kts"], "./gradlew build"),
    (".venv", &["pyproject.toml", "requirements.txt", "setup.py"], "python -m venv .venv"),
    ("venv", &["pyproject.toml", "requirements.txt", "setup.py"], "python -m venv venv"),
    ("Pods", &["Podfile"], "pod install"),
    ("vendor", &["composer.json"], "composer install"),
    ("vendor", &["Gemfile"], "bundle install"),
    ("_build", &["dune-project"], "dune build"),
    ("_build", &["rebar.config"], "rebar3 compile"),
    ("dist-newstyle", &["cabal.project"], "cabal build"),
    ("zig-cache", &["build.zig"], "zig build"),
    ("zig-out", &["build.zig"], "zig build"),
];

/// Directory names that mean the same thing wherever they appear.
///
/// The generic ones are only trusted when their parent vouches for them, in
/// `classify` below — a directory called `registry` or `cache` proves nothing
/// on its own.
const ALWAYS: &[(&str, Category)] = &[
    ("_cacache", Category::PackageCache),
    (".gradle", Category::PackageCache),
    ("registry", Category::PackageCache),
    ("toolchains", Category::PackageCache),
    #[cfg(target_os = "macos")]
    ("DerivedData", Category::AppCache),
    #[cfg(target_os = "macos")]
    ("Caches", Category::AppCache),
    // The XDG cache root, and the two package managers that most often fill it.
    #[cfg(not(target_os = "macos"))]
    (".cache", Category::AppCache),
    #[cfg(not(target_os = "macos"))]
    ("repository", Category::PackageCache),
    #[cfg(not(target_os = "macos"))]
    ("thumbnails", Category::AppCache),
];

/// File extensions that are only ever a disk image: libvirt's `qcow2`, the
/// VirtualBox and VMware formats, Apple's sparsebundle. Nothing else writes
/// these, so the name alone is proof.
const IMAGE_EXTS: &[&str] = &["qcow2", "vmdk", "vdi", "sparsebundle", "vhd", "vhdx"];

/// Extensions that are usually a disk image and occasionally something
/// irreplaceable. `.raw` is Docker's disk on macOS and also what Panasonic and
/// Leica cameras write; `.img` is a VM disk and also installer media and
/// forensic captures.
///
/// Every other rule in this module refuses to match on a name alone — a
/// `target` needs a `Cargo.toml` beside it, because "name-only matching would
/// eventually stage someone's photos". These two are precisely that hazard, and
/// they reach `--reclaim --yes`, where nobody is watching.
///
/// Size is the corroboration available. A VM disk is provisioned in gigabytes;
/// a camera raw is tens of megabytes. There is an order of magnitude of clear
/// air between them, so the floor sits in the middle of it. Below the floor the
/// entry is not offered at all, which for a file that small costs the user
/// nothing worth having.
///
/// Measured against `st_size` rather than allocated blocks, because the
/// question here is what the file *is*, not what it currently costs: a
/// freshly-created `Docker.raw` is provisioned at 60G and sparse down to almost
/// nothing, and it is a VM disk either way. What it costs is `--min-size`'s
/// question, and it is asked separately.
const AMBIGUOUS_IMAGE_EXTS: &[&str] = &["raw", "img"];
const AMBIGUOUS_IMAGE_FLOOR: u64 = 1 << 30;

/// The command that rebuilds this directory, for the entries we can name one
/// for. Same sibling test as `classify`, so the answer is the tool that
/// actually made it rather than a guess from the directory's name.
pub fn rebuild_command(name: &str, siblings: &HashSet<&str>) -> Option<&'static str> {
    BUILD_DIRS
        .iter()
        .find(|(dir, markers, _)| *dir == name && markers.iter().any(|m| siblings.contains(m)))
        .map(|(_, _, cmd)| *cmd)
}

/// Classify one entry, given its length and the names of everything beside it
/// in the same directory. `parent_name` disambiguates the generic names: a
/// `registry` directory only means Cargo's inside `.cargo`. `len` is `st_size`,
/// and corroborates the two ambiguous image extensions; see
/// [`AMBIGUOUS_IMAGE_EXTS`].
pub fn classify(
    name: &str,
    is_dir: bool,
    len: u64,
    parent_name: &str,
    siblings: &HashSet<&str>,
) -> Option<Category> {
    if !is_dir {
        // A dotfile has no extension: `.img` is a name, not an img file.
        let Some((stem, ext)) = name.rsplit_once('.') else { return None };
        if stem.is_empty() {
            return None;
        }
        let ext = ext.to_ascii_lowercase();
        if IMAGE_EXTS.contains(&ext.as_str()) {
            return Some(Category::VmImage);
        }
        if AMBIGUOUS_IMAGE_EXTS.contains(&ext.as_str()) && len >= AMBIGUOUS_IMAGE_FLOOR {
            return Some(Category::VmImage);
        }
        return None;
    }

    for (dir, markers, _) in BUILD_DIRS {
        if name == *dir && markers.iter().any(|m| siblings.contains(m)) {
            return Some(Category::BuildArtifact);
        }
    }

    for (dir, cat) in ALWAYS {
        if name != *dir {
            continue;
        }
        // The generic names need their parent to vouch for them.
        let ok = match *dir {
            "registry" | "toolchains" => matches!(parent_name, ".cargo" | ".rustup"),
            "Caches" => parent_name == "Library",
            "repository" => parent_name == ".m2",
            // Only the XDG cache root itself, not every `.cache` in a project.
            ".cache" => crate::paths::home().is_some_and(|h| {
                h.file_name().is_some_and(|n| n == parent_name)
            }),
            "thumbnails" => parent_name == ".cache",
            _ => true,
        };
        if ok {
            return Some(*cat);
        }
    }
    None
}
