//! Built-in knowledge of what commonly eats a Mac's disk and is safe to lose.
//!
//! Matching is done on a directory's *siblings*, not on its name alone. A
//! folder called `target` is only a Rust build directory when there is a
//! `Cargo.toml` next to it; `node_modules` only means what you think next to a
//! `package.json`. Name-only matching would eventually stage someone's photos.

use std::collections::HashSet;

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
pub enum Category {
    /// Virtual machine and container disk images. Usually the single biggest
    /// thing on a developer's Mac.
    VmImage,
    /// Rebuilt by running the build again.
    BuildArtifact,
    /// Re-downloaded on demand.
    PackageCache,
    /// Regenerated by the app that owns them.
    AppCache,
}

impl Category {
    pub fn label(self) -> &'static str {
        match self {
            Category::VmImage => "VM images",
            Category::BuildArtifact => "build artifacts",
            Category::PackageCache => "package caches",
            Category::AppCache => "app caches",
        }
    }

    /// What the user needs to know before staging the whole category.
    pub fn note(self) -> &'static str {
        match self {
            Category::VmImage => "the VM or container must be stopped first",
            Category::BuildArtifact => "rebuilt by your next build",
            Category::PackageCache => "re-downloaded on demand",
            Category::AppCache => "regenerated by the app that owns them",
        }
    }

    pub fn all() -> [Category; 4] {
        [Category::VmImage, Category::BuildArtifact, Category::PackageCache, Category::AppCache]
    }
}

/// A build directory and the marker file that proves what it is.
const BUILD_DIRS: &[(&str, &[&str])] = &[
    ("node_modules", &["package.json"]),
    ("target", &["Cargo.toml"]),
    ("build", &["CMakeLists.txt", "build.gradle", "build.gradle.kts"]),
    (".venv", &["pyproject.toml", "requirements.txt", "setup.py"]),
    ("venv", &["pyproject.toml", "requirements.txt", "setup.py"]),
    ("Pods", &["Podfile"]),
    ("vendor", &["composer.json", "Gemfile"]),
];

/// Directory names that mean the same thing wherever they appear.
const ALWAYS: &[(&str, Category)] = &[
    ("DerivedData", Category::AppCache),
    ("Caches", Category::AppCache),
    ("_cacache", Category::PackageCache),
    (".gradle", Category::PackageCache),
    ("registry", Category::PackageCache),
    ("toolchains", Category::PackageCache),
];

/// File extensions that are always a disk image.
const IMAGE_EXTS: &[&str] = &["raw", "qcow2", "vmdk", "vdi", "img", "sparsebundle"];

/// Classify one entry, given the names of everything beside it in the same
/// directory. `parent_name` disambiguates the generic names: a `registry`
/// directory only means Cargo's inside `.cargo`.
pub fn classify(
    name: &str,
    is_dir: bool,
    parent_name: &str,
    siblings: &HashSet<&str>,
) -> Option<Category> {
    if !is_dir {
        let ext = name.rsplit_once('.').map(|(_, e)| e.to_ascii_lowercase());
        if let Some(ext) = ext {
            if IMAGE_EXTS.contains(&ext.as_str()) {
                return Some(Category::VmImage);
            }
        }
        return None;
    }

    for (dir, markers) in BUILD_DIRS {
        if name == *dir && markers.iter().any(|m| siblings.contains(m)) {
            return Some(Category::BuildArtifact);
        }
    }

    for (dir, cat) in ALWAYS {
        if name != *dir {
            continue;
        }
        // The generic names need their parent to vouch for them.
        let ok = match *dir {
            "registry" | "toolchains" => matches!(parent_name, ".cargo" | ".rustup"),
            "Caches" => parent_name == "Library",
            _ => true,
        };
        if ok {
            return Some(*cat);
        }
    }
    None
}
